version: "3.9"  # optional since v1.27.0
services:
 
  nginx:
    build: nginx/
    ports:
       - "80:80"
    
    networks:
      internal_routes:
        aliases:
          - nginx
 
  rabbitmq_create:
    image: rabbitmq  
    ports:
       - "5672:5672"
    networks:
      internal_routes:
        aliases:
          - rabbitmq
 
  mysql_repli:
    image: mysql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: rabbitmqdata
        MYSQL_PASSWORD: 123456    
    ports:
       - "3307:3306"
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
    networks:
      internal_routes:
        aliases:
          - mysql_repli
  mysql:
    image: mysql
    environment:
       MYSQL_ROOT_USER: root
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_DATABASE: rabbitmqdata
       MYSQL_PASSWORD: 123456
    ports:
       - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql 
    networks:
      internal_routes:
        aliases:
          - mysql

  user_list:
    build: list_user/
    volumes: 
       - ./list_user/:/app
    expose:
       - 5001
    networks:
      internal_routes:
        aliases:
          - user_list

  create_user:  
    build: create_user/
    volumes: 
       - ./create_user/:/app
    expose:
       - 5000
    networks:
      internal_routes:
        aliases:
          - create_user 
  
  data_subscriber:
    build: data_subscriber/
    volumes: 
      - ./data_subscriber/:/app
    restart: on-failure
    depends_on:
      - "rabbitmq_create"
    networks:
      internal_routes:

networks:
  internal_routes:      
